[variables]
NIXPACKS_NODE_VERSION = "22"
PYTHON = "python3"
NPM_CONFIG_PRODUCTION = "false"

[phases.setup]
nixPkgs = ["...", "python3", "gcc", "gnumake"]

[phases.install]
cmds = ["npm ci --include=dev"]
